packages:
  - .
allowBuilds:
  bufferutil: true
  esbuild: true
  sharp: true
  utf-8-validate: true
  workerd: true
fetchRetries: 5
fetchRetryFactor: 2
fetchRetryMaxtimeout: 120000
fetchRetryMintimeout: 10000
fetchTimeout: 120000
minimumReleaseAgeExclude:
  - astro@7.0.3
networkConcurrency: 8
onlyBuiltDependencies:
  - bufferutil
  - esbuild
  - sharp
  - utf-8-validate
  - workerd
overrides:
  devalue: 5.8.1
  ws: 8.20.1
  yaml: 2.8.4
